#!/bin/bash
#$ -q hpc@@colon
#$ -N mof_property_extract

## extract Largest Cavity Diameter, Pore Limiting Diameter, Surface Area, and Void Fraction for each MOF 
## and print into h2oco2properties.csv

touch F_mof_properties.csv

echo "MOF,LCD,PLD,SA,VF,VF Error" >> F_mof_properties.csv


for ((i=1;i<=9122;i++))
do

# obtain mof name from S_mofs.csv

mof=$(awk 'FNR=='$i' {print $1}' mofs.csv)

# extract properties

LCD=$(awk 'FNR==1 {print $2}' ${mof}.res)

PLD=$(awk 'FNR==1 {print $3}' ${mof}.res)

SA=$(grep '@' ${mof}.sa | awk 'FNR==1 {print $12}')

# move to MOF_properties directory to obtain void fraction

cd ../MOF_properties/${mof}/

if [ -d Output ]; then

cd Output/System_0


VF=$(grep 'Average Widom' out* | awk 'FNR==2 {print $5}')

VF_error=$(grep 'Average Widom' out* | awk 'FNR==2 {print $7}') 

# step back into main directory
cd ../../../..

else
# print that there is no henry coefficient

VF='Error'
VF_error=' no Void Fraction'

# step back into main directory

cd ../..
fi

# print values into Selectivity_mof_properties.csv

echo "${mof},${LCD},${PLD},${SA},${VF},${VF_error}" >> F_mof_properties.csv

cd zeo++-0.3/

# remove .cif, .res, and .sa files

#rm ${mof}.cif ${mof}.sa ${mof}.res



done
