#!/bin/bash

# submit void fraction simulations
# 8426
for ((i=1;i<=9122;i++))
do


mof=$(awk 'FNR=='$i' {print $1}' mofs.csv)

# copy raspa.sh and condor-sh to mof folders
cd ../

cp condor-sh raspa.sh MOF_properties/${mof}

# set up mof folder to run

cd MOF_properties/${mof}

sed -i 's/Placeholder/'${mof}'.cif/' condor-sh
sed -i 's/Foldername/'${mof}'/' condor-sh
sed -i 's/Foldername/'${mof}'/' raspa.sh
sed -i 's/Mof_//' ${mof}.cif
sed -i 's/500000/50000/' simulation.input

if [ ! -d Output ]
then

condor_submit condor-sh

fi

cd ../../zeo++-0.3

done


