#!/bin/bash

# 9122 mofs in MPN CoRE MOFs
for ((i=8000;i<=9122;i++))
do

# obtain mof name from mofs.csv (have to step out and back into CO2 directory)


mof=$(awk 'FNR=='$i' {print $1}' mofs.csv)
cd mofs

# remove existing folders of mofs
if [ -d ${mof} ]; then
rm -r ${mof}
fi

# create directory for each MOF
mkdir ${mof}
# copy input and run files into directory
cd ../../..
cp MPN_CoRE_MOFs/MPNN_CoRE-ASR/${mof}.cif /scratch365/jgonza26/Project_HC/N2O/mofs/${mof}
# copy cif file into unit cell determination folder
cp MPN_CoRE_MOFs/MPNN_CoRE-ASR/${mof}.cif /scratch365/jgonza26/Project_HC/unit_cell

cd Project_HC/N2O
#pwd
cp simulation.input mofs/${mof}
cp condor-sh mofs/${mof}
cp raspa.sh mofs/${mof}
#cp Tip4p.def mofs/${mofs}

cd ../unit_cell
touch out
module load python
python mof_unit.py > out
rm ${mof}.cif
cell1=$(awk 'FNR==2 {print $1}' out)
cell2=$(awk 'FNR==2 {print $2}' out)
cell3=$(awk 'FNR==2 {print $3}' out)
cd ../N2O

fcell="${cell1} ${cell2} ${cell3}"

# step into directory
cd mofs/${mof}

# replace 'Placeholder' with actual MOF name in input file
sed -i 's/Placeholder/'${mof}'/' simulation.input
sed -i 's/Placeholder/'${mof}'.cif/' condor-sh
sed -i 's/Foldername/'${mof}'/' condor-sh
sed -i 's/Foldername/'${mof}'/' raspa.sh
sed -i 's/Mof_//' ${mof}.cif
sed -i "s/1 1 1/$fcell/" simulation.input


# submit job
condor_submit condor-sh

# step back into main directory
cd ../..

done
